#ifndef __ARDESTAN_AUTO_GENERATED_HEADER_FILE__
#define __ARDESTAN_AUTO_GENERATED_HEADER_FILE__

#define NUM_OF_POLLING_OBJECTS  (1)
#define NUM_OF_EVENT_SCHEDULING_OBJECTS (0)
#define NUM_OF_LOADBANG_OBJECTS (1)

#endif
