//
// arobj_dfplayer_mini.hpp
//
// generated by the Ardestan programming language : Tue Dec 03 17:55:19 CST 2019
//

#ifndef __arobj_dfplayer_mini__h__
#define __arobj_dfplayer_mini__h__


#include <SoftwareSerial.h>
#include <DFRobotDFPlayerMini.h>

#define DFPLAYER_MINI_SERIAL_BAUD_RATE 9600
#define DFPLAYER_MINI_TIMEOUT 500
#define DFPLAYER_MINI_DEFAULT_VOLUME 20
//----------------------------------------------------------------------------
// type
//----------------------------------------------------------------------------

typedef struct {
	SoftwareSerial* 		serial	;
	DFRobotDFPlayerMini* 	player	;
} ARObjDfplayerMini;

//----------------------------------------------------------------------------
// declaration
//----------------------------------------------------------------------------

void init_func_dfplayer_mini(
    ARObject*        self      ,
    void*            __fields__,
    uint_fast8_t     argc      ,
    ARMessageType*   argt      ,
    ARValue*         argv
);

void trigger_func_dfplayer_mini(
    ARObject*        self      ,
    int32_t          inlet_no  ,
    void*            __fields__
);
#endif
